<a href="https://colab.research.google.com/github/FishStalkers/tutorials/blob/main/Brees_edits_NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a Python library that consists of multidimensional array objects and variations thereof along with hundreds of potential math functions for use. The package is one of the most useful for scientific computing and its versatility and power make it a common tool used by scientists of many disciplines. 

**Note: you most likely only need one or two paragraph between code **

**describe the data set here **

 The code below will install NumPy and load our dataset. 

In [ ]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()

**descirbe what you are doing here**

In [ ]:
#instantiate an array of integers
arr = np.array([0,1,2,3,4], dtype='int32')
print(arr)

[0 1 2 3 4]


Our first instantiated array! The beauty of NumPy is that we don't have to stick to 1d arrays. We can create 2d and 3d arrays too. 
**you can create higher order arrary then 3d***

In [ ]:
arr1 = np.array([[0,1,2, 3],[1,2,3,4]])
print(arr1)

[[0 1 2 3]
 [1 2 3 4]]


In [ ]:
arr2 = np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
print(arr2)

[[[ 2 17]
  [45 78]]

 [[88 92]
  [60 76]]

 [[76 33]
  [20 18]]]


From these, we can obtain information about different properties of our arrays.
**create a chart which give the defination of what this means? **

In [ ]:
#Dimension (number of dimensions the array is in)

print(arr1.ndim)

#Shape (Number of rows, columns, etc)

print(arr2.shape)

#Type (data type)

print(arr1.dtype)

#Size

print(arr2.size)

#Total bytes used within array

print(arr1.nbytes)

2
(3, 2, 2)
int64
12
64


We can also create matrices. Let's create a 0s matrix, a 1s matrix, and a matrix with random values.** what might we use matrices for? create a chart for these different functions**

In [ ]:
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.full((2,3), 2)

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Knowing what we know now about creating arrays and displaying array properties, let's take a preliminary look at our Iris dataset. 

In [ ]:
print(iris.data.ndim)
print(iris.data.shape)
print(iris.data.size)
print(iris.DESCR)


2
(150, 4)
600
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ==

Great! Now that we know how to look at basic properties, let's look at how to access information within our array. After all, thats what we want to do, right? **create a graph to look at the properties of the iris dataset**

In [ ]:
dset = iris.data
#gets data at row 2 column 3 within the data set
print(dset[2,3])
#gets the 0th row
print(dset[0,:])
#gets the 4th column
print(dset[:,3])
#gets the dataset with just the first 2 rows and first 3 columns
print(dset[0:2,0:3])


0.2
[5.1 3.5 1.4 0.2]
[0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2 0.4 0.4 0.3
 0.3 0.3 0.2 0.4 0.2 0.5 0.2 0.2 0.4 0.2 0.2 0.2 0.2 0.4 0.1 0.2 0.2 0.2
 0.2 0.1 0.2 0.2 0.3 0.3 0.2 0.6 0.4 0.3 0.2 0.2 0.2 0.2 1.4 1.5 1.5 1.3
 1.5 1.3 1.6 1.  1.3 1.4 1.  1.5 1.  1.4 1.3 1.4 1.5 1.  1.5 1.1 1.8 1.3
 1.5 1.2 1.3 1.4 1.4 1.7 1.5 1.  1.1 1.  1.2 1.6 1.5 1.6 1.5 1.3 1.3 1.3
 1.2 1.4 1.2 1.  1.3 1.2 1.3 1.3 1.1 1.3 2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8
 1.8 2.5 2.  1.9 2.1 2.  2.4 2.3 1.8 2.2 2.3 1.5 2.3 2.  2.  1.8 2.1 1.8
 1.8 1.8 2.1 1.6 1.9 2.  2.2 1.5 1.4 2.3 2.4 1.8 1.8 2.1 2.4 2.3 1.9 2.3
 2.5 2.3 1.9 2.  2.3 1.8]
[[5.1 3.5 1.4]
 [4.9 3.  1.4]]


A QR Factorization of a matrix is a matrix decomposed into two matrices, a Q orthogonal matrix and an R upper triangular matrix. This definition can be useful to solve linear least squares problems. **more explanation of what this is and when we might use it **

In [ ]:
#QR Factorization

q,r = np.linalg.qr(dset)
print(q)
print("\n")
print(r)

[[-7.05626410e-02 -1.12834741e-01 -5.35604521e-02 -4.85100071e-03]
 [-6.77954786e-02 -6.24183863e-02 -1.20670136e-01  1.78165913e-02]
 [-6.50283162e-02 -1.00753125e-01 -5.35114961e-02  2.22950789e-03]
 [-6.36447350e-02 -9.45630387e-02 -3.17963126e-02 -4.54412513e-02]
 [-6.91790598e-02 -1.32002110e-01 -1.39976581e-02 -2.41171190e-02]
 [-7.47133846e-02 -1.44083726e-01  9.88728158e-03  8.60478546e-03]
 [-6.36447350e-02 -1.32599221e-01  1.89089989e-02 -5.87823649e-03]
 [-6.91790598e-02 -1.06644655e-01 -4.38122165e-02 -2.95766068e-02]
 [-6.08775726e-02 -8.21828669e-02 -4.82006851e-02 -2.60570041e-02]
 [-6.77954786e-02 -7.50971138e-02 -8.78124351e-02 -5.67177541e-02]
 [-7.47133846e-02 -1.18726271e-01 -5.58281204e-02 -1.37119623e-02]
 [-6.64118974e-02 -1.19621938e-01  5.49881298e-03 -7.35683311e-02]
 [-6.64118974e-02 -6.89070279e-02 -1.01998095e-01 -3.55530539e-02]
 [-5.94939914e-02 -1.01350236e-01 -4.45387348e-02 -1.93340227e-02]
 [-8.02477094e-02 -1.30807887e-01 -1.03744868e-01  7.09881415e

The above code snipped is the QR decomposition for the Iris dataset. Now, knowing how to calculate it using NumPy, take the QR decomposition of the first 20 rows and the 4 columns. 

In [ ]:
#QR Example

#reduced = dset[0:15, 0:4]
#a,b = np.linalg.qr(reduced)
#print(a,b)

[[-0.26719154  0.03662755 -0.10805339 -0.02095792]
 [-0.25671344 -0.51332522 -0.02123156  0.45578013]
 [-0.24623534 -0.0047896  -0.08421544  0.08910074]
 [-0.24099629 -0.05294704  0.28310894 -0.03309335]
 [-0.26195249  0.29089536 -0.05915492 -0.24490457]
 [-0.28290869  0.3323125   0.23856879  0.53712314]
 [-0.24099629  0.40069084  0.12703173  0.17910707]
 [-0.26195249 -0.0115299   0.09849016 -0.0619381 ]
 [-0.23051819 -0.14926192  0.21385356  0.12858803]
 [-0.25671344 -0.36211259  0.14111715 -0.28478107]
 [-0.28290869  0.02988725 -0.08612862 -0.09078284]
 [-0.25147439  0.19458047  0.35393219 -0.32686493]
 [-0.25147439 -0.41027004  0.02609904 -0.16333342]
 [-0.22527914  0.10500589 -0.21959045 -0.37897399]
 [-0.30386489  0.07130439 -0.75308988  0.12401415]] [[-1.90874304e+01 -1.30085608e+01 -5.49209599e+00 -7.79570622e-01]
 [ 0.00000000e+00  6.61320433e-01 -6.44893860e-03  1.64682849e-01]
 [ 0.00000000e+00  0.00000000e+00  6.21964697e-01  9.58018142e-02]
 [ 0.00000000e+00  0.00000000e+00

Now, let's see if we can calculate the singular value decomposition of  a matrix. The SVD splits an m x n matrix into 3 component matrices and has useful applications in data analysis. Let's compute the SVD of the dataset. 

In [ ]:
#SVD
u,s,v = np.linalg.svd(dset)
print(u)
print("\n")
print(s)
print("\n")
print(v)

[[-0.06161685  0.12961144  0.0021386  ... -0.09343429 -0.09573864
  -0.08085465]
 [-0.05807094  0.11101978  0.07067239 ...  0.03690405 -0.03153954
   0.01309526]
 [-0.05676305  0.11796647  0.00434255 ...  0.03066199  0.19531473
   0.13569909]
 ...
 [-0.0940593  -0.0498297  -0.04144001 ...  0.98181631 -0.02194514
  -0.00894446]
 [-0.09488961 -0.05610123 -0.21297821 ... -0.02155617  0.94178018
  -0.02971961]
 [-0.08847836 -0.0515697  -0.09575285 ... -0.0086052  -0.03021088
   0.9736599 ]]
[95.95991387 17.76103366  3.46093093  1.88482631]
[[-0.75110816 -0.38008617 -0.51300886 -0.16790754]
 [ 0.2841749   0.5467445  -0.70866455 -0.34367081]
 [ 0.50215472 -0.67524332 -0.05916621 -0.53701625]
 [ 0.32081425 -0.31725607 -0.48074507  0.75187165]]


Now, your turn to try it. Calculate the SVD of the sliced dataset that includes the first 10 rows and the first 4 columns.

In [ ]:
#SVD Example

#a,b,c = np.linalg.svd(reduced)
#print(a)
#print("\n")
#print(b)
#print("\n")
#print(c)

[[-0.26704521 -0.11066054 -0.03140721  0.01738833 -0.27368054 -0.53925713
  -0.41198453 -0.26083093 -0.25566703 -0.11460699 -0.25865731 -0.27885163
  -0.10885347 -0.13097278 -0.2439751 ]
 [-0.24875324  0.24820627 -0.39495006 -0.5080559   0.30925677 -0.12744394
   0.14728436 -0.04610544 -0.26423189 -0.2006681   0.01347605  0.24650459
  -0.29590604  0.25999895 -0.02273523]
 [-0.24562987 -0.06894253 -0.04048153 -0.09465784 -0.1201167   0.29660856
   0.13542884  0.05903985  0.20407795  0.05986168 -0.12950022  0.27452809
  -0.03491378 -0.29946226 -0.75618706]
 [-0.24188986  0.27024534  0.0926867   0.04465838 -0.17570798  0.44405184
   0.18435967 -0.13386487 -0.02503556 -0.43123888 -0.10857974 -0.3687045
  -0.30966316 -0.29705879  0.24381636]
 [-0.26597027 -0.20045092  0.18219998  0.26944236  0.84864853  0.00812578
  -0.07213261 -0.05961446  0.01176123 -0.04628431 -0.08159977 -0.13907341
  -0.01540374 -0.14601188 -0.06647277]
 [-0.28960987  0.03225769  0.46586622 -0.48367292 -0.01922978  0.3

overall notes: 
1.) missing examples
examples need to relate to biology

2.) missing images you need to generate images of the topics you are discussing or reference supporting images from online

3.) remember anything taken from online must be cited

4.) you need to add information on tranpose and inverse matrics before svd and QR

5.) you should briefly show the math of the function you are discussing 
